kind: Deployment
apiVersion: apps/v1
metadata:
  name: mariadb
  namespace: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: tobi312/rpi-mariadb:10.3
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: drupal
            - name: MYSQL_USER
              value: drupal
            - name: MYSQL_PASSWORD
              value: drupal
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
          volumeMounts:
            - mountPath: /var/lib/mysql/
              name: database
          resources:
            limits:
              cpu: "2"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: mariadb-pvc
