name: Test with K3d

on: [push]

jobs:
  dev_env:
    runs-on: ubuntu-latest # [self-hosted, linux, x64]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Make scripts executable
        run: find scripts/ -type f -iname "*.sh" -exec chmod +x {} \;

      - name: Prerare the K3d development environment
        run: scripts/k3d_cluster.sh
        shell: bash
